name: ecspresso deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_ROLE_NAME }}

      - run: aws ecs list-clusters
      - uses: actions/checkout@v4
      - run: sudo apt -y install parallel
      - uses: kayac/ecspresso@v2
        with:
          version: latest
      - name: parallel ecspresso deploy
        shell: bash -euo pipefail {0}
        run: |
          ls ecspresso*.yml | parallel --delay 5 --line-buffer --tagstring "[{#}]" \
          "TIME=$(date +%s) ecspresso deploy --config {} 2>&1 | tee /tmp/{/.}.log; echo \${PIPESTATUS[0]} > /tmp/{/.}.exit"
          "TIME=$(date +%s) ecspresso deploy --config {} 2>&1 | tee /tmp/{/.}.log; echo >> /tmp/{/.}.log; echo \${PIPESTATUS[0]} > /tmp/{/.}.exit"
          for f in ecspresso*.yml; do echo -e "\n=== $f ==="; cat /tmp/${f%.yml}.log; done
          exit $(cat /tmp/*.exit | sort -nr | head -n1)
