name: ecspresso deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_ROLE_NAME }}

      - run: aws ecs list-clusters
      - run: sudo apt -y install parallel
      - name: parallel
        run: |
          parallel --line-buffer --tagstring "[{#}]" ::: \
          "for i in {1..5}; do echo 0; sleep 1; done | tee /tmp/output0" \
          "for i in {1..5}; do echo 1; sleep 1; done | tee /tmp/output1"; \
          cat /tmp/output0 /tmp/output1

