name: ecspresso deploy

on:
  push:
    paths:
      - "app/**"

jobs:
  invoke-get-changelist:
    uses: ./.github/workflows/get-changelist.yml
    with:
      target-path: app/
    permissions:
      pull-requests: read
      contents: read

  get-ecspresso-configs:
    runs-on: ubuntu-latest
    needs: [invoke-get-changelist]
    outputs:
      yml: ${{ steps.get-ecspresso-configs.outputs.yml }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: get ecspresso config yaml files
        id: get-ecspresso-configs
        shell: bash
        env:
          APP_LIST: ${{ github.event.inputs.app-list && github.event.inputs.app-list) || needs.invoke-get-changelist.outputs.app-list }}
        run: |
          echo "APP_LIST: $APP_LIST"
          YAML=$(echo "$APP_LIST" | jq -r '.[] | if type=="object" then .["app-name"] else . end' | xargs -I{} find "app/{}" -maxdepth 1 -name 'ecspresso*.yml' -type f 2>/dev/null | jq -R . | jq -sc .)

          echo "yml=$YAML" >> $GITHUB_OUTPUT

  dir:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [invoke-get-changelist]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        app: ${{ github.event.inputs.app-list && fromJson(github.event.inputs.app-list) || fromJson(needs.invoke-get-changelist.outputs.app-list) }}
    steps:
      - run: pwd

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [dir, get-ecspresso-configs]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        yml: ${{ fromJson(needs.get-ecspresso-configs.outputs.yml) }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_ROLE_NAME }}

      - run: aws ecs list-clusters
      - uses: actions/checkout@v4
#      - run: sudo apt -y install parallel
      - uses: kayac/ecspresso@v2
        with:
          version: latest
      - run: |
          DIR=$(dirname "${{ matrix.yml }}")
          FILE=$(basename "${{ matrix.yml }}")
          cd $DIR
          pwd
          ls $FILE
          ecspresso verify --config=$FILE
#      - name: parallel ecspresso deploy
#        shell: bash -euo pipefail {0}
#        run: |
#          ls ecspresso*.yml | parallel --delay 5 --line-buffer --tagstring "[{#}]" \
#          "TIME=$(date +%s) ecspresso deploy --config {} 2>&1 | tee /tmp/{/.}.log; echo \${PIPESTATUS[0]} > /tmp/{/.}.exit"
#          for f in ecspresso*.yml; do echo; echo -e " \n=== $f ==="; cat /tmp/${f%.yml}.log; done
#          exit $(cat /tmp/*.exit | sort -nr | head -n1)
